import { Header, Wrapper, Flex, AssetContainer, CryptoSymbol, Quantity } from "./styles/assets.styles";

const Assets = () => {
  return(
    <Wrapper><Flex>
      <Header>SPOT Assets</Header>
      
        <AssetContainer>
          <CryptoSymbol>
            BTC
          </CryptoSymbol>
          <Quantity>
            0.436537
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            ETH
          </CryptoSymbol>
          <Quantity>
            1.2347
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            BTC
          </CryptoSymbol>
          <Quantity>
            0.436537
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            ETH
          </CryptoSymbol>
          <Quantity>
            1.2347
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            BTC
          </CryptoSymbol>
          <Quantity>
            0.436537
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            ETH
          </CryptoSymbol>
          <Quantity>
            1.2347
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            BTC
          </CryptoSymbol>
          <Quantity>
            0.436537
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            ETH
          </CryptoSymbol>
          <Quantity>
            1.2347
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            BTC
          </CryptoSymbol>
          <Quantity>
            0.436537
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            ETH
          </CryptoSymbol>
          <Quantity>
            1.2347
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            BTC
          </CryptoSymbol>
          <Quantity>
            0.436537
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            ETH
          </CryptoSymbol>
          <Quantity>
            1.2347
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            BTC
          </CryptoSymbol>
          <Quantity>
            0.436537
          </Quantity>
        </AssetContainer>
        <AssetContainer>
          <CryptoSymbol>
            ETH
          </CryptoSymbol>
          <Quantity>
            1.2347
          </Quantity>
        </AssetContainer>
      </Flex>
    </Wrapper>
  )
}

export default Assets;